Custom Errors Upgrade
stabilitydao/stability-platform-contracts pull request #34
Opened 2023-11-13 13:16 UTC by JodsMigel

2023-11-13 13:36 UTC, a17 requested changes

2023-11-13 13:36 UTC, a17 commented on src/core/Factory.sol
> +            revert VaultImplementationIsNotAvailable();
add `string vaultType` arg

2023-11-13 13:36 UTC, a17 commented on src/core/Factory.sol
> +            revert VaultNotAllowedToDeploy();
add `string vaultType` arg

2023-11-13 13:36 UTC, a17 commented on src/core/Factory.sol
> +            revert StrategyImplementationIsNotAvailable();
add `string strategyId` arg

2023-11-13 13:36 UTC, a17 commented on src/core/Factory.sol
> +            revert StrategyLogicNotAllowedToDeploy();
add `string strategyId` arg

2023-11-13 13:36 UTC, a17 commented on src/core/Factory.sol
> +        if(!vaultConfig[vaultTypeHash].upgradeAllowed){
add `bytes32 vaultTypeHash` arg

2023-11-13 13:36 UTC, a17 commented on src/core/Factory.sol
> +            revert UpgradeDenied();
add `bytes32 strategyIdHash` arg

2023-11-13 13:36 UTC, a17 commented on src/core/Factory.sol
> +            revert AlreadyLastVersion();
add `bytes32 strategyIdHash` arg

2023-11-13 14:00 UTC, JodsMigel commented on src/core/Factory.sol
> +            revert VaultImplementationIsNotAvailable();
Not need to do

2023-11-13 14:00 UTC, JodsMigel commented on src/core/Factory.sol
> +            revert VaultNotAllowedToDeploy();
Not need to do

2023-11-13 14:01 UTC, JodsMigel commented on src/core/Factory.sol
> +            revert StrategyImplementationIsNotAvailable();
Not need to do

2023-11-13 14:01 UTC, JodsMigel commented on src/core/Factory.sol
> +            revert StrategyLogicNotAllowedToDeploy();
Not need to do

2023-11-13 15:09 UTC, a17 approved these changes

2023-11-13 20:19 UTC, a17 approved these changes

2023-11-14 18:55 UTC, a17 approved these changes

2023-11-14 19:04 UTC, merged